cred/urls.py
from django.conf.urls import patterns, url
from django.conf import settings

urlpatterns = patterns('cred.views',
    # New list views
    url(r'^list/$', 'list'),
    url(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/$', 'list'),
    url(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/sort-(?P<sortdir>ascending|descending)-by-(?P<sort>\w+)/$', 'list'),
    url(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/sort-(?P<sortdir>ascending|descending)-by-(?P<sort>\w+)/page-(?P<page>\d+)/$', 'list'),

    # Search dialog for mobile
    url(r'^search/$', 'search'),

    # Single cred views
    url(r'^detail/(?P<cred_id>\d+)/$', 'detail'),
    url(r'^detail/(?P<cred_id>\d+)/fingerprint/$', 'ssh_key_fingerprint'),
    url(r'^detail/(?P<cred_id>\d+)/download/$', 'downloadattachment'),
    url(r'^detail/(?P<cred_id>\d+)/ssh_key/$', 'downloadsshkey'),
    url(r'^edit/(?P<cred_id>\d+)/$', 'edit'),
    url(r'^delete/(?P<cred_id>\d+)/$', 'delete'),
    url(r'^add/$', 'add'),

    # Adding to the change queue
    url(r'^addtoqueue/(?P<cred_id>\d+)/$', 'addtoqueue'),

    # Bulk views (for buttons on list page)
    url(r'^addtoqueue/bulk/$', 'bulkaddtoqueue'),
    url(r'^delete/bulk/$', 'bulkdelete'),
    url(r'^undelete/bulk/$', 'bulkundelete'),
    url(r'^addtag/bulk/$', 'bulktagcred'),

    # Tags
    url(r'^tag/$', 'tags'),
    url(r'^tag/add/$', 'tagadd'),
    url(r'^tag/edit/(?P<tag_id>\d+)/$', 'tagedit'),
    url(r'^tag/delete/(?P<tag_id>\d+)/$', 'tagdelete'),
)

if not settings.RATTIC_DISABLE_EXPORT:
    urlpatterns += patterns('cred.views',
        # Export views
        url(r'^export.kdb$', 'download'),
        url(r'^export-by-(?P<cfilter>\w+)/(?P<value>[^/]*).kdb$', 'download'),
    )

ratticweb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from tastypie.api import Api
from cred.api import CredResource, TagResource
from staff.api import GroupResource
from django.conf import settings

# Configure the error handlers
handler500 = 'ratticweb.views.handle500'
handler404 = 'ratticweb.views.handle404'

# Setup the API
v1_api = Api(api_name='v1')
v1_api.register(CredResource())
v1_api.register(TagResource())
v1_api.register(GroupResource())

# Setup the base paths for applications, and the API
base_urlpatterns = patterns('',
    # Apps:
    url(r'^$', 'ratticweb.views.home', name='home'),
    url(r'^account/', include('account.urls')),
    url(r'^cred/', include('cred.urls')),
    url(r'^staff/', include('staff.urls')),
    url(r'^help/', include('help.urls')),

    # API
    url(r'^api/', include(v1_api.urls)),

    # Language
    (r'^i18n/', include('django.conf.urls.i18n')),

    # two Factor
    # url(r'^', include('two_factor.urls', namespace='two_factor')),
)

# If in debug mode enable the Django admin interface
if settings.DEBUG:
    # Uncomment the next two lines to enable the admin:
    from django.contrib import admin
    admin.autodiscover()

    base_urlpatterns += patterns('',
        # Uncomment the admin/doc line below to enable admin documentation:
        url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

        # Uncomment the next line to enable the admin:
        url(r'^admin/', include(admin.site.urls)),
    )

# Strip any leading slash from the RATTIC_ROOT_URL
if settings.RATTIC_ROOT_URL[0] == '/':
    root = settings.RATTIC_ROOT_URL[1:]
else:
    root = settings.RATTIC_ROOT_URL

# Serve RatticDB from an alternate root if requested
urlpatterns = patterns('',
    url(r'^' + root, include(base_urlpatterns)),
)

# Serve the static files from the right location in dev mode
urlpatterns += staticfiles_urlpatterns()

staff/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from views import NewUser, UpdateUser

urlpatterns = patterns('staff.views',
    # Views in views.py
    url(r'^$', 'home'),

    # User/Group Management
    url(r'^userdetail/(?P<uid>\d+)/$', 'userdetail'),
    url(r'^removetoken/(?P<uid>\d+)/$', 'removetoken'),
    url(r'^groupdetail/(?P<gid>\d+)/$', 'groupdetail'),

    # Auditing
    url(r'^audit-by-(?P<by>\w+)/(?P<byarg>\d+)/$', 'audit'),

    # Importing
    url(r'^import/keepass/$', 'upload_keepass'),
    url(r'^import/process/$', 'import_overview'),
    url(r'^import/process/(?P<import_id>\d+)/$', 'import_process'),
    url(r'^import/process/(?P<import_id>\d+)/ignore/$', 'import_ignore'),

    # Undeletion
    url(r'^credundelete/(?P<cred_id>\d+)/$', 'credundelete'),
)

# URLs we remove if using LDAP groups
if not settings.USE_LDAP_GROUPS:
    urlpatterns += patterns('staff.views',
        # Group Management
        url(r'^groupadd/$', 'groupadd'),
        url(r'^groupedit/(?P<gid>\d+)/$', 'groupedit'),
        url(r'^groupdelete/(?P<gid>\d+)/$', 'groupdelete'),
        url(r'^useredit/(?P<pk>\d+)/$', UpdateUser.as_view(), name="user_edit"),
        url(r'^userdelete/(?P<uid>\d+)/$', 'userdelete'),
    )

# User add is disabled only when LDAP config exists
if not settings.LDAP_ENABLED:
    urlpatterns += patterns('staff.views',
        # User Management
        url(r'^useradd/$', NewUser.as_view(), name="user_add"),

    )

cred/models.py
from django.db import models
from django.db.models import Q
from django.contrib import admin
from django.contrib.auth.models import User, Group
from django.utils.translation import ugettext_lazy as _
from django.forms.models import model_to_dict
from django.utils.timezone import now
from django.conf import settings

from ratticweb.util import DictDiffer, field_file_compare
from ssh_key import SSHKey
from fields import SizedFileField
from storage import CredAttachmentStorage


class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __unicode__(self):
        return self.name

    def visible_count(self, user):
        return Cred.objects.visible(user).filter(tags=self).count()


class CredIconAdmin(admin.ModelAdmin):
    list_display = ('name', 'filename')


class SearchManager(models.Manager):
    def visible(self, user, historical=False, deleted=False):
        usergroups = user.groups.all()
        qs = super(SearchManager, self).get_query_set()

        if not user.is_staff or not deleted:
            qs = qs.exclude(is_deleted=True, latest=None)

        if not historical:
            qs = qs.filter(latest=None)

        qs = qs.filter(Q(group__in=usergroups)
                     | Q(latest__group__in=usergroups)
                     | Q(groups__in=usergroups)
                     | Q(latest__groups__in=usergroups)).distinct()

        return qs

    def change_advice(self, user, grouplist=[]):
        logs = CredAudit.objects.filter(
            # Get a list of changes done
            Q(cred__group__in=grouplist, audittype=CredAudit.CREDCHANGE) |
            # Combined with a list of views from this user
            Q(cred__group__in=grouplist, audittype__in=[CredAudit.CREDVIEW, CredAudit.CREDPASSVIEW, CredAudit.CREDADD, CredAudit.CREDEXPORT], user=user)
        ).order_by('time', 'id')

        # Go through each entry in time order
        tochange = []
        for l in logs:
            # If this user viewed the password then change it
            if l.audittype in (CredAudit.CREDVIEW, CredAudit.CREDPASSVIEW, CredAudit.CREDADD, CredAudit.CREDEXPORT):
                tochange.append(l.cred.id)
            # If there was a change done not by this user, dont change it
            if l.audittype == CredAudit.CREDCHANGE and l.user != user:
                if l.cred.id in tochange:
                    tochange.remove(l.cred.id)

        # Fetch the list of credentials to change from the DB for the view
        return Cred.objects.filter(id__in=tochange)


class Cred(models.Model):
    METADATA = ('description', 'descriptionmarkdown', 'group', 'groups', 'tags', 'iconname', 'latest', 'id', 'modified', 'attachment_name', 'ssh_key_name')
    SORTABLES = ('title', 'username', 'group', 'id', 'modified')
    APP_SET = ('is_deleted', 'latest', 'modified', 'attachment_name', 'ssh_key_name')
    objects = SearchManager()

    # User changable fields
    title = models.CharField(verbose_name=_('Title'), max_length=64, db_index=True)
    url = models.URLField(verbose_name=_('URL'), blank=True, null=True, db_index=True)
    username = models.CharField(verbose_name=_('Username'), max_length=250, blank=True, null=True, db_index=True)
    password = models.CharField(verbose_name=_('Password'), max_length=250, blank=True, null=True)
    descriptionmarkdown = models.BooleanField(verbose_name=_('Markdown Description'), default=False, )
    description = models.TextField(verbose_name=_('Description'), blank=True, null=True)
    group = models.ForeignKey(Group, verbose_name=_('Group'))
    groups = models.ManyToManyField(Group, verbose_name=_('Groups'), related_name="child_creds", blank=True, null=True, default=None)
    tags = models.ManyToManyField(Tag, verbose_name=_('Tags'), related_name='child_creds', blank=True, null=True, default=None)
    iconname = models.CharField(verbose_name=_('Icon'), default='Key.png', max_length=64)
    ssh_key = SizedFileField(verbose_name=_('SSH key'), storage=CredAttachmentStorage(), max_upload_size=settings.RATTIC_MAX_ATTACHMENT_SIZE, null=True, blank=True, upload_to='not required')
    attachment = SizedFileField(verbose_name=_('Attachment'), storage=CredAttachmentStorage(), max_upload_size=settings.RATTIC_MAX_ATTACHMENT_SIZE, null=True, blank=True, upload_to='not required')

    # Application controlled fields
    is_deleted = models.BooleanField(default=False, db_index=True)
    latest = models.ForeignKey('Cred', related_name='history', blank=True, null=True, db_index=True)
    modified = models.DateTimeField(db_index=True)
    created = models.DateTimeField(auto_now_add=True)

    ssh_key_name = models.CharField(max_length=64, null=True, blank=True)
    attachment_name = models.CharField(max_length=64, null=True, blank=True)

    def save(self, *args, **kwargs):
        try:
            # Get a copy of the old object from the db
            old = Cred.objects.get(id=self.id)

            # Reset the primary key so Django thinks its a new object
            old.id = None

            # Set the latest on the old copy to the new copy
            old.latest = self

            # Create it in the DB
            old.save()

            # Add the tags to the old copy now that it exists
            for t in self.tags.all():
                old.tags.add(t)

            # Add the groups
            for g in self.groups.all():
                old.groups.add(g)

            # Lets see what was changed
            oldcred = model_to_dict(old)
            newcred = model_to_dict(self)
            diff = DictDiffer(newcred, oldcred).changed()

            # Ohhhkaaay, so the attachment field looks like its changed every
            # time, so we do a deep comparison, if the files match we remove
            # it from the list of changed fields.
            for field in ('attachment', 'ssh_key'):
                if field_file_compare(oldcred[field], newcred[field]):
                    diff = diff - set((field, ))

            # Check if some non-metadata was changed
            chg = diff - set(Cred.METADATA)
            cred_changed = len(chg) > 0

            # If the creds were changed update the modify date
            if cred_changed:
                self.modified = now()
        except Cred.DoesNotExist:
            # This just means its new cred, set the initial modified time
            self.modified = now()

        super(Cred, self).save(*args, **kwargs)

    def delete(self):
        if not self.is_deleted:
            self.is_deleted = True
            self.save()
        else:
            super(Cred, self).delete()

    def on_changeq(self):
        return CredChangeQ.objects.filter(cred=self).exists()

    def is_latest(self):
        return self.latest is None

    def is_owned_by(self, user):
        # Staff can do anything
        if user.is_staff:
            return True

        # If its the latest and in your group you can see it
        if not self.is_deleted and self.latest is None and self.group in user.groups.all():
            return True

        # If the latest is in your group you can see it
        if not self.is_deleted and self.latest is not None and self.latest.group in user.groups.all():
            return True

        return False

    def is_visible_by(self, user):
        # Staff can see anything
        if user.is_staff:
            return True

        # If its the latest and (in your group or it belongs to a viewer group you also belong to) you can see it
        if not self.is_deleted and self.latest is None and (self.group in user.groups.all() or any([g in user.groups.all() for g in self.groups.all()])):
            return True

        # If the latest is in your group you can see it
        if not self.is_deleted and self.latest is not None and (self.latest.group in user.groups.all() or any([g in user.groups.all() for g in self.latest.groups.all()])):
            return True

        return False

    def ssh_key_fingerprint(self):
        return SSHKey(self.ssh_key.read(), self.password).fingerprint()

    def __unicode__(self):
        return self.title.encode('utf-8')


class CredAdmin(admin.ModelAdmin):
    list_display = ('title', 'username', 'group')


class CredAudit(models.Model):
    CREDADD = 'A'
    CREDCHANGE = 'C'
    CREDMETACHANGE = 'M'
    CREDVIEW = 'V'
    CREDEXPORT = 'X'
    CREDPASSVIEW = 'P'
    CREDDELETE = 'D'
    CREDSCHEDCHANGE = 'S'
    CREDAUDITCHOICES = (
        (CREDADD, _('Added')),
        (CREDCHANGE, _('Changed')),
        (CREDMETACHANGE, _('Only Metadata Changed')),
        (CREDVIEW, _('Only Details Viewed')),
        (CREDEXPORT, _('Exported')),
        (CREDDELETE, _('Deleted')),
        (CREDSCHEDCHANGE, _('Scheduled For Change')),
        (CREDPASSVIEW, _('Password Viewed')),
    )

    audittype = models.CharField(max_length=1, choices=CREDAUDITCHOICES)
    cred = models.ForeignKey(Cred, related_name='logs')
    user = models.ForeignKey(User, related_name='credlogs')
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        get_latest_by = 'time'
        ordering = ('-time',)


class CredAuditAdmin(admin.ModelAdmin):
    list_display = ('audittype', 'user', 'cred', 'time')


class CredChangeQManager(models.Manager):
    def add_to_changeq(self, cred):
        return self.get_or_create(cred=cred)

    def for_user(self, user):
        return self.filter(cred__in=Cred.objects.visible(user))


class CredChangeQ(models.Model):
    objects = CredChangeQManager()

    cred = models.ForeignKey(Cred, unique=True)
    time = models.DateTimeField(auto_now_add=True)


class CredChangeQAdmin(admin.ModelAdmin):
    list_display = ('cred', 'time')


admin.site.register(CredAudit, CredAuditAdmin)
admin.site.register(Cred, CredAdmin)
admin.site.register(Tag)
admin.site.register(CredChangeQ, CredChangeQAdmin)

staff/templates/staff_audit.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block content %}

{% include "staff_part_audit_filter.html" %}

{% if by == 'cred' %}
  <h2>{% blocktrans with cred_title=item.title %}Audit Logs for password &apos;{{ cred_title }}&apos;{% endblocktrans %}</h2>
{% endif %}
{% if by == 'user' %}
  <h2>{% blocktrans with username=item.username %}Audit Logs for user &apos;{{ username }}&apos;{% endblocktrans %}</h2>
{% endif %}
{% if by == 'days' %}
  <h2>{% blocktrans %}Audit Logs going back {{ item }} days ago{% endblocktrans %}</h2>
{% endif %}

<table class="table table-striped table-bordered table-condensed">
<tr>

    <th>
        {% trans "Action" %}
        <a href="#filterModal" data-toggle="modal"><i class="icon-filter"></i></a>
    </th>

  {% if type != 'user' %}
    <th>{% trans "User" %}</th>
  {% endif %}
  {% if type != 'cred' %}
    <th>{% trans "Credential" %}</th>
  {% endif %}
  <th>{% trans "When" %}</th>
</tr>

{% for audit in logs %}
  <tr>
    <td>{{ audit.get_audittype_display }}</td>
    {% if by != 'user' %}
      <td><a href="{% url 'staff.views.userdetail' audit.user.id %}">{{ audit.user.username }}</a></td>
    {% endif %}
    {% if vy != 'cred' %}
      <td><a href="{% url 'cred.views.detail' audit.cred.id %}">{{ audit.cred.title }}</a></td>
    {% endif %}
    <td>{{ audit.time }}</td>
  </tr>
{% endfor %}
</table>

<div class="pagination pagination-centered">
  <ul>
    {% if logs.has_previous %}
      <li><a href="?page={{ logs.previous_page_number }}">{% trans "Prev" %}</a></li>
    {% else %}
      <li class="disabled"><a href="#">{% trans "Prev" %}</a></li>
    {% endif %}
    {% for p in logs.paginator.page_range %}
      {% if logs.number == p %}
        <li class="active"><a href="#">{{ p }}</a></li>
      {% else %}
        <li><a href="?page={{ p }}">{{ p }}</a></li>
      {% endif %}
    {% endfor %}
    {% if logs.has_next %}
      <li><a href="?page={{ logs.next_page_number }}">{% trans "Next" %}</a></li>
    {% else %}
      <li class="disabled"><a href="#">{% trans "Next" %}</a></li>
    {%endif %}
  </ul>
</div>

{% endblock %}

staff/templates/staff_changeadvice.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block content %}
<h2>{% blocktrans with username=viewuser.username %}Changes for user: {{ username }}{% endblocktrans %}</h2>
<p>{% blocktrans %}We noticed that you are disabling a user account, or removing groups
from a user. To help you RatticDB has analysed the auditlogs to see what
passwords the user knows, and no longer has access to. We recommend that
you add all these passwords to the change queue. To do this press the
&quot;Add to Change Queue&quot; button, if you don't want to change some
of the passwords, simply uncheck them first.{% endblocktrans %}</p>

<form method="POST" action="{% url "cred.views.bulkaddtoqueue" %}">{% csrf_token %}
<table class="table table-striped table-bordered table-condensed">
<thead>
<tr>
    <th><input onclick="copycheckbox('all', 'credcheck')" type="checkbox" checked="true" name="all" value="" /></th>
    <th>{% trans "Title" %}</th>
    <th>{% trans "User" %}</th>
    <th>{% trans "Group" %}</th>
    <th>{% trans "Tags" %}</th>
</tr>
</thead>
<tbody>
{% for c in creds %}
<tr>
    <td><input type="checkbox" checked="true" name="credcheck" value="{{ c.id }}" /></td>
    <td><a href="{% url "cred.views.detail" c.id %}">{{ c.title }}</a></td>
    <td>{{ c.username }}</td>
    <td>{{ c.group.name }}</td>
    <td>{% for t in c.tags.all %}{% if not forloop.first %}, {% endif %}<a href="{% url "cred.views.list" "tag" t.id %}">{{ t.name }}</a>{% endfor %}</td>
</tr>
{% endfor %}
</tbody>
</table>
<input type="submit" class="btn" value="{% trans "Add to Change Queue" %}" />
</form>

{% endblock %}

staff/templates/staff_groupdetail.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block content %}
{% if delete %}
<h1>{% trans "Delete Group" %}: {{ group.name }}</h1>
<div class="alert alert-error">{% blocktrans %}Deleting this group will delete every password underneath it.{% endblocktrans %}</div>
{% else %}
<h1>{% trans "Group" %} {{ group.name }}</h1>
{% if not USE_LDAP_GROUPS %}
<div class="btn-group">
    <a class="btn" href="{% url "staff.views.groupedit" group.id %}">{% trans "Edit" %}</a>
    <a class="btn btn-danger" href="{% url "staff.views.groupdelete" group.id %}">{% trans "Delete" %}</a> 
</div>
<br /><br />
{% endif %}
{% endif %}
<table class="table table-striped table-bordered table-condensed">
<tr><th>{% trans "Name" %}</th><td>{{ group.name }}</td></tr>
<tr><th>{% trans "Users" %}</th><td>{% for u in group.user_set.all %}<a href="{% url "staff.views.userdetail" u.id %}">{{ u.username }}</a>, {% endfor %}</td></tr>
<tr><th>{% trans "Passwords" %}</th><td>{% for c in group.cred_set.all %}<a href="{% url "cred.views.detail" c.id %}">{{ c.title }}</a>, {% endfor %}</td></tr>
</table>
{% if delete %}
    <form action="{% url "staff.views.groupdelete" group.id %}" method="post">{% csrf_token %}
        <input type="submit" class="btn btn-danger" value="{% trans "Delete forever" %}" />
    </form>
{% endif %}
{% endblock %}

staff/templates/staff_groupedit.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block content %}
<h1>{% if not group %}{% trans "Create Group" %}{% else %}{% trans "Edit Group" %}: {{ group.name }}{% endif %}</h1>
<form class="form-horizontal" action="" method="post">{% csrf_token %}
    {% for field in form %}
        <div class="control-group">
            {{ field.errors }}
            <label class="control-label" for="{{ field.html_name }}">{{ field.label }}</label>
            <div class="controls">
                {{ field }}
            </div>
        </div>
    {% endfor %}
    <div class="controls">
        <input class="btn btn-primary" type="submit" value="{% trans "Submit" %}" />
    </div>
</form>
{% endblock %}

staff/templates/staff_home.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block title %}{% trans "Staff" %} - {% trans "Rattic" %}{% endblock %}

{% block content %}
<h1>{% trans "Staff Manage" %}</h1>

<div class="btn-group">
  {% if not LDAP_ENABLED %}
    <a class="btn" href="{% url "user_add" %}">{% trans "Add User" %}</a>
  {% endif %}

  {% if not USE_LDAP_GROUPS %}
    <a class="btn" href="{% url "staff.views.groupadd" %}">{% trans "Add Group" %}</a>
  {% endif %}
  <a class="btn" href="{% url "staff.views.upload_keepass" %}">{% trans "Import Keepass" %}</a>
  <a class="btn" href="{% url "cred.views.list" 'special' 'trash' %}">{% trans "View Trash" %}</a>
  <a class="btn" href="{% url "staff.views.audit" "days" 7 %}">{% trans "Audit One Week" %}</a>
</div>

<h2>{% trans "Users" %}</h2>
<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>{% trans "Username" %}</th>
    <th>{% trans "email" %}</th>
    {% if not LDAP_ENABLED %}
    <th>{% trans "Edit" %}</th>
    <th>{% trans "Delete" %}</th>
    {% endif %}
  </tr>
{% for u in userlist %}
<tr {% if not u.is_active %}class="error"{% endif %}>
  <td><a href="{% url "staff.views.userdetail" u.id %}">{{ u.username }}</a></td>
  <td>{{ u.email }}</td>
  {% if not LDAP_ENABLED %}
  <td><a href="{% url "user_edit" u.id %}">{% trans "Edit" %}</a></td>
  <td><a href="{% url "staff.views.userdelete" u.id %}">{% trans "Delete" %}</a></td>
  {% endif %}
</tr>
{% endfor %}
</table>

<h2>{% trans "Access Groups" %}</h2>
<table class="table table-striped table-bordered table-condensed">
  <tr><th>{% trans "Name" %}</th>{% if not USE_LDAP_GROUPS %}<th>{% trans "Edit" %}</th><th>{% trans "Delete" %}</th>{% endif %}</tr>
{% for g in grouplist %}
<tr>
  <td><a href="{% url "staff.views.groupdetail" g.id %}">{{ g.name }}</a></td>
  {% if not USE_LDAP_GROUPS %}
    <td><a href="{% url "staff.views.groupedit" g.id %}">{% trans "Edit" %}</a></td>
    <td><a href="{% url "staff.views.groupdelete" g.id %}">{% trans "Delete" %}</a></td>
  {% endif %}
</tr>
{% endfor %}
</table>
{% endblock %}

staff/templates/staff_import_overview.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block content %}
<h1>{% trans "Import Overview" %}</h1>
<table class="table table-striped table-bordered table-condensed">
<thead>
<tr>
    <th>{% trans "Actions" %}</th>
    <th>{% trans "Title" %}</th>
    <th>{% trans "User" %}</th>
</tr>
</thead>
<tbody>
{% for e in entries %}
<tr>
    <td>
        <a class="btn btn-mini btn-success" href="{% url "staff.views.import_process" forloop.counter0 %}">{% trans "Import" %}</a>
        <a class="btn btn-mini btn-danger" href="{% url "staff.views.import_ignore" forloop.counter0 %}">{% trans "Skip" %}</a>
    </td>
    <td>{{ e.title }}</td>
    <td>{{ e.username }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

staff/templates/staff_import_process.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}
{% load credicons %}

{% block content %}

{% include "cred_part_passgenmodal.html" %}
{% include "cred_part_logomodal.html" with icons=icons txtfield='#id_iconname' imgfield='#logodisplay' %}
<h1>{% trans "Password Import" %}</h1>

<form class="form-horizontal" enctype="multipart/form-data" autocomplete="off" method="post">{% csrf_token %}
    {% for field in form %}
        <div class="control-group">
            {{ field.errors }}
            <label class="control-label" for="{{ field.html_name }}">{{ field.label }}</label>
            <div class="controls">
              {{ field }}
            </div>
        </div>
    {% endfor %}
    <div class="controls">
        <input id="credsave" class="btn btn-primary" type="submit" value="{% trans "Submit" %}" />
    </div>
</form>
{% endblock %}

staff/templates/staff_keepassimport.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block headarea %}
  {% if user.is_staff and not USE_LDAP_GROUPS %}
    <meta name="rattic_attach_new_group_buttons" content="true" />
  {% else %}
    <meta name="rattic_attach_new_group_buttons" content="false" />
  {% endif %}
{% endblock %}


{% block content %}

<h1>{% trans "Keepass Import" %}</h1>
<p>{% blocktrans %}We recommend that you import your keepass data into a
seperate group, then adjust the group on each password as required.{% endblocktrans %}</p>
<form enctype="multipart/form-data" class="form-horizontal" action="" method="post">{% csrf_token %}
    {% for field in form %}
        <div class="control-group">
            {{ field.errors }}
            <label class="control-label" for="{{ field.html_name }}">{{ field.label }}</label>
            <div class="controls">
                {{ field }}
            </div>
        </div>
    {% endfor %}
    <div class="controls">
        <input class="btn btn-primary" type="submit" value="{% trans "Submit" %}" />
    </div>
</form>
{% endblock %}

staff/templates/staff_removetoken.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<h1>Disable Two Factor</h1>
<p>Are you sure you wish to remove Two Factor Authentication from 
{{ user.username }}?</p>
<form method="post">
{% csrf_token %}
<input class="btn btn-danger" type="submit" value="Confirm" />
</form>
{% endblock %}